name = "GtkExtensions"
uuid = "6ae3132a-a620-11e8-33dd-0137428a80dd"
authors = ["Jonathan Bieler <jonathan.bieler@alumni.epfl.ch>"]
version = "0.1.0"

[deps]
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
